version: '3'

services:
  db:
    image: postgres:14.3
    container_name: littleshopdb
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data